# Generated by Django 5.2.1 on 2025-05-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Помещение',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('длина', models.FloatField(verbose_name='Длина, м')),
                ('ширина', models.FloatField(verbose_name='Ширина, м')),
                ('высота', models.FloatField(verbose_name='Высота, м')),
                ('кол_окон', models.IntegerField(default=0, verbose_name='Количество окон')),
                ('ширина_окна', models.FloatField(default=0, verbose_name='Ширина окна, м')),
                ('высота_окна', models.FloatField(default=0, verbose_name='Высота окна, м')),
                ('кол_дверей', models.IntegerField(default=0, verbose_name='Количество дверей')),
                ('ширина_двери', models.FloatField(default=0, verbose_name='Ширина двери, м')),
                ('высота_двери', models.FloatField(default=0, verbose_name='Высота двери, м')),
            ],
        ),
    ]
