# Generated by Django 5.2.1 on 2025-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100, verbose_name='Название')),
                ('ширина_рулона', models.FloatField(verbose_name='Ширина рулона, м')),
                ('длина_рулона', models.FloatField(verbose_name='Длина рулона, м')),
                ('текстура', models.ImageField(upload_to='wallpapers/', verbose_name='Текстура')),
            ],
        ),
    ]
